name: twotp
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  base32: ^1.1.1
  shared_preferences: ^0.5.6+1
  flutter_bloc: ^3.1.0
  equatable: ^1.0.3
  path_provider: ^1.6.0
  uuid: ^2.0.4
  flutter_secure_storage: ^3.3.1+1
  qr_code_scanner: ^0.0.12
  flutter_svg: ^0.17.4
  line_icons:
    git:
      url: "https://github.com/galonsos/line_icons.git"
  local_auth: ^0.6.2+2
  permission_handler: ^5.0.0+hotfix.5
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/graphics/
  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-ExtraLight.otf
          weight: 200
        - asset: fonts/Manrope-Light.otf
          weight: 300
        - asset: fonts/Manrope-Regular.otf
          weight: 400
        - asset: fonts/Manrope-Medium.otf
          weight: 500
        - asset: fonts/Manrope-SemiBold.otf
          weight: 600
        - asset: fonts/Manrope-Bold.otf
          weight: 700
        - asset: fonts/Manrope-ExtraBold.otf
          weight: 800
    - family: JetBrainsMono
      fonts:
          - asset: fonts/JetBrainsMono-Regular.ttf
            weight: 400
          - asset: fonts/JetBrainsMono-Medium.ttf
            weight: 500
          - asset: fonts/JetBrainsMono-Bold.ttf
            weight: 700
          - asset: fonts/JetBrainsMono-ExtraBold.ttf
            weight: 800
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
